### ISSUE TITLE
Compatibility issue with Mythic Mobs -- herobrine:survivor seems to be trying something?

### ISSUE THREAD

**Issue by ArmandVestibule** [Alex-MacLean/TheLegendOfHerobrine#47]
**Describe the bug**
Server crash when Survivor activity affects Mythic Mobs kobolds

**To Reproduce**
Run a Fabric server with the latest version of Mythic Mobs and LoH

**Expected behavior**
No breaky.

**Environment**
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 5.15.0-83-generic
	Java Version: 17.0.8, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 2966428936 bytes (2829 MiB) / 7516192768 bytes (7168 MiB) up to 7516192768 bytes (7168 MiB)
	CPUs: 3
	Processor Vendor: GenuineIntel
	Processor Name: Intel Core Processor (Skylake, IBRS)
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Fabric API 0.14.22
	Mod version 0.7.2 (1.20.1)

**Additional context**
```
java.lang.ClassCastException: class net.pixeldream.mythicmobs.entity.KoboldEntity cannot be cast to class net.minecraft.class_1588 (net.pixeldream.mythicmobs.entity.KoboldEntity and net.minecraft.class_1588 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @7f9a81e8)
	**at com.herobrinemod.herobrine.entities.SurvivorEntity.method_5958(SurvivorEntity.java:154)**
	at net.minecraft.class_1308.method_6023(class_1308.java:788)
	at net.minecraft.class_1309.method_6007(class_1309.java:2673)
	at net.minecraft.class_1308.method_6007(class_1308.java:550)
	at net.minecraft.class_1296.method_6007(class_1296.java:128)
	at net.minecraft.class_1309.method_5773(class_1309.java:2419)
	at net.minecraft.class_1308.method_5773(class_1308.java:351)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Alex-MacLean** [comment]
This is from the survivor making hostile mobs target it. The code I used to make it is rather ugly and I may just end up removing it altogether

**Comment by Alex-MacLean** [comment]
I just removed the offending code in a500fed65d9a96228382ac69c50a173f47086f1c

The feature was interesting but was a compatibility nightmare with mods that used inheritance from MobEntity.class rather poorly. I'll close this issue when I release a version with this patch

**Comment by Alex-MacLean** [comment]
Fixed in 0.8.0 release
